### PR TITLE
Upgrade to the current version 0.10.0 of bevy

### PR DESCRIPTION
**Pull request by ehasnain**
Thank you very much for the wonderful tutorial video.
We can update the repository to 0.10.0 now as it was released a month ago.

- update main.rs, player.rs, enemy/mod.rs
- add development build optimizations as suggested by the bevy docs

### CODE REVIEW

**Comment by jeremychone** [comment]
@ehasnain this is super cool! Thank you so much. 

Give me a few days, and I will merge it.

Do not hesitate to ping me if I did not get to it. This is awesome!

**Comment by ehasnain** [comment]
Thank you @jeremychone :)

**Comment by jeremychone** [comment]
@ehasnain sorry for the delay. Was traveling. I just merged it, I will update the readme and video description.

**Comment by jeremychone** [comment]
Ok, done, YouTube description update, readme updated. Thanks again for this bevy 0.10 update... This is why we love open source!

**Comment by ehasnain** [comment]
Thank you @jeremychone! Have a good one. Looking forward to more of your great works. 😊

**Pull request merged**
